### ISSUE TITLE
Can't deposit ether into fuel

### ISSUE THREAD

**Issue by molekilla** [FuelLabs/fuel-js#14]
Here is the sample code with my implementation

```
import fuel from '@fuel-js/wallet';

// use the window provider key / account / eth_signTypedData_v4 for transaction signing
const k = '..'
const wallet = new fuel.Wallet(null, {
    privateKey: k
});

(async () => {
  // get your address
  console.log('my address', wallet.address);
  
    // make a deposit
    await wallet.deposit('0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', fuel.utils.parseEther('0.0003'));
  
    // make a transfer
    await wallet.transfer('0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', '0xD1d9D81f07e579f77c8C7A4580Bcf1c8F8af09fe', fuel.utils.parseEther('0.0002'));
  
    // listen for new inputs and balance changes
    wallet.on('input', input => {
      console.log('listening for new inputs: ', input);
    });
  
  
  })();
```

error
```

/home/rogelio/Code/fuel/node_modules/ethers/errors.js:76
    var error = new Error(message);
                ^
Error: contract not deployed (contractAddress="0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", operation="getDeployed", version=4.0.48)
    at Object.throwError (/home/rogelio/Code/fuel/node_modules/ethers/errors.js:76:17)
    at /home/rogelio/Code/fuel/node_modules/ethers/contract.js:353:32
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Promise.all (index 0)
    at Wallet.deposit (/home/rogelio/Code/fuel/node_modules/@fuel-js/wallet/src/index.js:558:20)
```

**Comment by SilentCicero** [comment]
So as described in the Wallet SDK docs: https://docs.fuel.sh/v1.0.0/SDK/Wallet.html#deposit

The first argument is the address of the ERC20 token contract. It will then attempt to transfer from the `wallet.address` account, an amount of tokens into that account.

This error is just saying there is no ERC20 contract at address: `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` it can talk to.

**Comment by molekilla** [comment]
I tried with bat, then Sai and those returned the same Sent from HUAWEI Mate 10 Pro-------- Original Message --------Subject: Re: [FuelLabs/fuel-js] Can't deposit ether into fuel (#14)From: Nick Dodson To: FuelLabs/fuel-js CC: Rogelio Morrell ,Author 
So as described in the Wallet SDK docs: https://docs.fuel.sh/v1.0.0/SDK/Wallet.html#deposit
The first argument is the address of the ERC20 token contract. It will then attempt to transfer from the wallet.address account, an amount of tokens into that account.
This error is just saying there is no ERC20 contract at address: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee it can talk to.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FuelLabs/fuel-js/issues/14#issuecomment-756233587",
"url": "https://github.com/FuelLabs/fuel-js/issues/14#issuecomment-756233587",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SilentCicero** [comment]
@molekilla which network, are you talking about Mainnet or Rinkeby?

The wallet defaults to rinkeby currently.

**Comment by molekilla** [comment]
That's it, let me check it out Sent from HUAWEI Mate 10 Pro-------- Original Message --------Subject: Re: [FuelLabs/fuel-js] Can't deposit ether into fuel (#14)From: Nick Dodson To: FuelLabs/fuel-js CC: Rogelio Morrell ,Mention 
@molekilla which network, are you talking about Mainnet or Rinkeby?
The wallet defaults to rinkeby currently.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FuelLabs/fuel-js/issues/14#issuecomment-756244519",
"url": "https://github.com/FuelLabs/fuel-js/issues/14#issuecomment-756244519",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SilentCicero** [comment]
Closing for now, as this has gone stale. Please try the latest library and let me know if you have any issues. As always try with the testnet first before using mainnet. Feel free to re-open if you have issues.
