### ISSUE TITLE
Package only supports Node 12

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/fuel-js#2]
The package.json file only allows fuel-core to be added to Node 12. If the code is compatible with earlier versions of Node, this restriction should be decreased.

**Comment by SilentCicero** [comment]
This was due to some unfortunate requirements of our Lambda providers.

In the future, more of the lib will be in different packages and this requirement will likely be removed.

I think you can just use --ignore-engines on many NPM / Yarn systems.

**Comment by dmihal** [comment]
Ya I think the solution is splitting this into multiple repos (client code, node code, server lambdas, contracts, etc).

Not a high priority, but I imagine developers might start running into this issue, especially since many popular Ethereum libraries don't work on Node 12 (unfortunately 😢).
