### ISSUE TITLE
Question about passing tokenId in the retrieve method

### ISSUE THREAD

**Issue by QiuDaniel** [FuelLabs/fuel-js#20]
I found in the source code of the retrieve method that the tokenId passed in by _inputs is 0, which should be the Id of Ether. What if I want to retrieve other ERC20 tokens? Is it a bug here?

**Comment by SilentCicero** [comment]
So currently the wallet will retrieve any withdrawals available. The `anytoken` flag is set, which nullified the zero specified. This will likely change in the future to allow for more specificity.

Also a reminder there is a two week withdrawal period if your meaning to withdraw from Fuel v1 atm.

Definitely reach me on Discord if you have further questions.

**Comment by QiuDaniel** [comment]
> So currently the wallet will retrieve any withdrawals available. The `anytoken` flag is set, which nullified the zero specified. This will likely change in the future to allow for more specificity.
> 
> Also a reminder there is a two week withdrawal period if your meaning to withdraw from Fuel v1 atm.
> 
> Definitely reach me on Discord if you have further questions.

> Thank you for your reply.
> There is such a code in the _inputs method source code
`  // If the token id is not correct, skip.
      if (!decodedInput.properties.token().get().eq(tokenId)) {
        continue;
      }`
> In the for loop, those whose tokenId is not 0 will be skipped, even if the `anytoken` flag is set

**Comment by SilentCicero** [comment]
I'll look into this now, thank you!

**Comment by SilentCicero** [comment]
Going to re-work this API, you should be able to specify token Id, also looks like some anytoken edge cases your correct! So going to patch this for the next release.

Thank you!

**Comment by SilentCicero** [comment]
As of @fuel-js/wallet@0.5.8 you can now specify the token Id you would like to retrieve. More to come in the docs soon.

Should be: ```js
wallet.retrieve(tokenId, opts)
``` now. Let me know if you have any future issues. Closing for now.
