### ISSUE TITLE
RaidGuild Request: indexed.wtf doc edits and additions

### ISSUE THREAD

**Issue by kittyslasher** [FuelLabs/fuel-js#28]
Hello blessed devs,

We here at Raid Guild have brought you indexed.wtf and are taking care to make sure the docs we display for each Layer 2 and side-chain project are accurate and filled with information the dev teams would like to highlight specifically. Having easily accessible information about all these solutions will bring more attention to your project.

Please find the markdown for the docs for your project below.

Kindly review, edit and provide any missing details and information at your taste and discretion as project leaders.

Moving forward we aim to keep indexed.wtf as current and beneficial to developers researching the ecosystem as possible. Please feel free at any time to submit an issue or PR to update the displayed information.

Thank you for your attention to this matter.

Best,
The Indexed Army
We stand for accurate data.

www.RaidGuild.org
@chair28980 @kittyslasher

```markdown

# Fuel Labs Docs
<!-- Please update description if necessary. Please feel free to update/eliminate/include headers below.-->

## Name
Fuel Labs

## Description
Fuel is a permissionless and trustless layer-2 protocol for Ethereum, targeted at low-cost high-throughput value-transfer transactions. Fuel is powered by a highly-optimized optimistic rollup design.

## Consensus Type
[Optimistic Rollup](https://medium.com/matter-labs/optimistic-vs-zk-rollup-deep-dive-ea141e71e075)

## Tx Cost
1350-1600 gas

## Average TPS
500 TPS 

## Governance/validator Token
None

## Transactional Token
 ⧫ ETH + Any ERC20 Token ⧫

## Resources
[Website](https://fuel.sh/)
[Docs](https://docs.fuel.sh/v1.1.0/Introduction/Welcome.html)
[Github](https://github.com/fuellabs)



## Social Media & Community
[Twitter](https://twitter.com/fuellabs_?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)
[Discord](https://discord.gg/xfpK4Pe)
[Medium](https://fuellabs.medium.com/)
```

**Comment by kittyslasher** [comment]
Since this was closed does this mean you don't want the project listed? Projects been pre funded and we aren't asking for payment just updated information on fuel labs

**Comment by adlerjohn** [comment]
This isn't the appropriate place for this kind of inquiry. Please use the community Discord for such questions.

**Comment by kittyslasher** [comment]
![image](https://user-images.githubusercontent.com/79062064/111084503-e8935b00-84cf-11eb-859a-96c89854f16d.png)
